### ISSUE TITLE
When source is a table, bot makes a mess.

### ISSUE THREAD

**Issue by starcitsura** [JakeLane/WolframAlpha-Reddit-Bot#4]
The comment [here](https://www.reddit.com/r/IAmA/comments/3d9luh/were_scientists_on_the_nasa_new_horizons_team/ct3587x) did not use table formatting, and created a unreadable mess.

**Comment by JakeLane** [comment]
This is a difficult one, as the output is not consistent enough to create a parser for. This means that MathML from the WolframAlpha API would need to be used which the wrapper is not compatible with.

**Comment by JakeLane** [comment]
Fixed by consequence of the character limit. Tables can now be view in a image.
