### ISSUE TITLE
unit clarifications are not used

### ISSUE THREAD

**Issue by TimSorbet** [JakeLane/WolframAlpha-Reddit-Bot#5]
See https://www.reddit.com/r/theydidthemath/comments/3eawan/request_how_fast_would_they_have_to_go_to_make_it/ctdbtqp?context=1 and the Wolfram-Alpha link http://www.wolframalpha.com/input/?i=sqrt%2810+cm+*+2+%2F+g%29&a=UnitClash_*g.*StandardAccelerationOfGravity--

The Wolfram-Alpha page correctly has a result in units of time, because it understood that "g" referred to acceleration due to gravity, not grams. The bot did not include this unit clarification and came up with a nonsensical answer in units of [mass]^-1/2 [length]^1/2. If possible, the bot should pick up these unit clarifications to show the correct result.

**Comment by JakeLane** [comment]
Implemented in c36983941478fa4d1b4d8112b114d2a21f985218.
