### ISSUE TITLE
Bot replies to [time in some timezone] in my local time

### ISSUE THREAD

**Issue by paulblakely** [JakeLane/WolframAlpha-Reddit-Bot#6]
Which leads to information of very limited usefulness :)

See https://www.reddit.com/r/starcitizen/comments/3fmu9y/gamescom_8pm_what_time_zone_is_this/ctq3aio

**Comment by JakeLane** [comment]
Unfortunately, this cannot be solved due to constraints from the WolframAlpha API.

**Comment by JakeLane** [comment]
I just realised that WolframAlpha generally will say if it uses the ip.
