### ISSUE TITLE
Assumption of Australian currency

### ISSUE THREAD

**Issue by eblume** [JakeLane/WolframAlpha-Reddit-Bot#7]
Not sure if this is a bug or not but the bot seems to assume Australian currency, as per this post: https://www.reddit.com/r/pics/comments/3fsh54/a_marine_proposing/ctrupbf

The post in question was assuming US currency, which makes sense in that context.

**Comment by JakeLane** [comment]
It uses Australia currency because WolframAlpha uses GeoIP and the bot is hosted in Australia. I guess it would be best to specify a location in the US as most of Reddit is from there anyway.

**Comment by JakeLane** [comment]
Added ability to chose country in config (bot is running on Los Angeles).

**Comment by eblume** [comment]
:+1:
