### ISSUE TITLE
Violates terms of use

### ISSUE THREAD

**Issue by AdamTReineke** [JakeLane/WolframAlpha-Reddit-Bot#8]
http://www.wolframalpha.com/termsofuse/

> The Wolfram|Alpha service may be used only by a human being using a conventional web browser to manually enter queries one at a time. Because Wolfram|Alpha is doing computation, not just lookup, each query may require significant CPU time on multiple parallel servers. Any attempt to use a robot, script, or organized group of humans to repeatedly access Wolfram|Alpha could place an unacceptable load on the system, and is strictly forbidden.

**Comment by JakeLane** [comment]
That is the terms of use for the website, not the [API](http://products.wolframalpha.com/api/termsofuse.html).
